name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'  # Gatilho para tags que seguem o padrão vX.X.X

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Descrição das mudanças na versão ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./caminho/para/seu/modulo.zip  # Atualize com o caminho do seu módulo
          asset_name: modulo-v${{ github.ref }}.zip
          asset_content_type: application/zip
